name: Github Action demo for building and publish a docker image
on: push
jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet
        run: |
          echo "Hello world"
      - name: Git version
        run: |
          git --version
      - name: Git commit
        run: |
          git config --global user.name "Github action"
          git config --global user.email ""
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          echo "Hello world" > hello.md
          git add -A .
          git commit -m "Automated hello world"
          git push
