name: Github Action demo for building and publish a docker image
on: push
jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet
        run: |
          echo "Hello world"
      - name: Git version
        run: |
          git --version
      - name: Git config
        run: |
          git config
