name: Github Action demo
on: push
jobs:
  unit_tests:
    name: Run demo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [18.12.1, 20.12.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install npm dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
